package companies

import (
	"errors"
)

type CompaniesGetResponse_companies_email_address_email_opt_status int

const (
	UNENGAGED_MARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS CompaniesGetResponse_companies_email_address_email_opt_status = iota
	SINGLE_OPT_IN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	DOUBLE_OPT_IN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	CONFIRMED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	UNENGAGED_NON_MARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	NON_MARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	LOCKDOWN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	BOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	HARD_BOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	MANUAL_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	ADMIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	SYSTEM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	LIST_UNSUBSCRIBE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	FEEDBACK_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	SPAM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	INVALID_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	DEACTIVATED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
)

func (i CompaniesGetResponse_companies_email_address_email_opt_status) String() string {
	return []string{"UNENGAGED_MARKETABLE", "SINGLE_OPT_IN", "DOUBLE_OPT_IN", "CONFIRMED", "UNENGAGED_NON_MARKETABLE", "NON_MARKETABLE", "LOCKDOWN", "BOUNCE", "HARD_BOUNCE", "MANUAL", "ADMIN", "SYSTEM", "LIST_UNSUBSCRIBE", "FEEDBACK", "SPAM", "INVALID", "DEACTIVATED"}[i]
}
func ParseCompaniesGetResponse_companies_email_address_email_opt_status(v string) (any, error) {
	result := UNENGAGED_MARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	switch v {
	case "UNENGAGED_MARKETABLE":
		result = UNENGAGED_MARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "SINGLE_OPT_IN":
		result = SINGLE_OPT_IN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "DOUBLE_OPT_IN":
		result = DOUBLE_OPT_IN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "CONFIRMED":
		result = CONFIRMED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "UNENGAGED_NON_MARKETABLE":
		result = UNENGAGED_NON_MARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "NON_MARKETABLE":
		result = NON_MARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "LOCKDOWN":
		result = LOCKDOWN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "BOUNCE":
		result = BOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "HARD_BOUNCE":
		result = HARD_BOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "MANUAL":
		result = MANUAL_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "ADMIN":
		result = ADMIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "SYSTEM":
		result = SYSTEM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "LIST_UNSUBSCRIBE":
		result = LIST_UNSUBSCRIBE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "FEEDBACK":
		result = FEEDBACK_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "SPAM":
		result = SPAM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "INVALID":
		result = INVALID_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	case "DEACTIVATED":
		result = DEACTIVATED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_ADDRESS_EMAIL_OPT_STATUS
	default:
		return 0, errors.New("Unknown CompaniesGetResponse_companies_email_address_email_opt_status value: " + v)
	}
	return &result, nil
}
func SerializeCompaniesGetResponse_companies_email_address_email_opt_status(values []CompaniesGetResponse_companies_email_address_email_opt_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i CompaniesGetResponse_companies_email_address_email_opt_status) isMultiValue() bool {
	return false
}
