package v2

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// AffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder builds and executes requests for operations under \v2\affiliates\commissionPrograms\subscriptionCommissionPrograms\{commission_program_id}
type AffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewAffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilderInternal instantiates a new AffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder and sets the default values.
func NewAffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder {
	m := &AffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/affiliates/commissionPrograms/subscriptionCommissionPrograms/{commission_program_id}", pathParameters),
	}
	return m
}

// NewAffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder instantiates a new AffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder and sets the default values.
func NewAffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewAffiliatesCommissionProgramsSubscriptionCommissionProgramsWithCommission_program_ItemRequestBuilderInternal(urlParams, requestAdapter)
}
