package v2

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// AffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder builds and executes requests for operations under \v2\affiliates\commissionPrograms\{commission_id}:removeSubscriptionCommission
type AffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewAffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilderInternal instantiates a new AffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder and sets the default values.
func NewAffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder {
	m := &AffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/affiliates/commissionPrograms/{commission_id}:removeSubscriptionCommission", pathParameters),
	}
	return m
}

// NewAffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder instantiates a new AffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder and sets the default values.
func NewAffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *AffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewAffiliatesCommissionProgramsWithCommission_idRemoveSubscriptionCommissionRequestBuilderInternal(urlParams, requestAdapter)
}
