package item

import (
	"errors"
)

type ContactIdPatchResponse_source_type int

const (
	APPOINTMENT_CONTACTIDPATCHRESPONSE_SOURCE_TYPE ContactIdPatchResponse_source_type = iota
	FORMAPIHOSTED_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	FORMAPIINTERNAL_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	WEBFORM_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	INTERNALFORM_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	LANDINGPAGE_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	IMPORT_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	MANUAL_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	API_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	OTHER_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	UNKNOWN_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
)

func (i ContactIdPatchResponse_source_type) String() string {
	return []string{"APPOINTMENT", "FORMAPIHOSTED", "FORMAPIINTERNAL", "WEBFORM", "INTERNALFORM", "LANDINGPAGE", "IMPORT", "MANUAL", "API", "OTHER", "UNKNOWN"}[i]
}
func ParseContactIdPatchResponse_source_type(v string) (any, error) {
	result := APPOINTMENT_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	switch v {
	case "APPOINTMENT":
		result = APPOINTMENT_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "FORMAPIHOSTED":
		result = FORMAPIHOSTED_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "FORMAPIINTERNAL":
		result = FORMAPIINTERNAL_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "WEBFORM":
		result = WEBFORM_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "INTERNALFORM":
		result = INTERNALFORM_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "LANDINGPAGE":
		result = LANDINGPAGE_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "IMPORT":
		result = IMPORT_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "MANUAL":
		result = MANUAL_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "API":
		result = API_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "OTHER":
		result = OTHER_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	case "UNKNOWN":
		result = UNKNOWN_CONTACTIDPATCHRESPONSE_SOURCE_TYPE
	default:
		return 0, errors.New("Unknown ContactIdPatchResponse_source_type value: " + v)
	}
	return &result, nil
}
func SerializeContactIdPatchResponse_source_type(values []ContactIdPatchResponse_source_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ContactIdPatchResponse_source_type) isMultiValue() bool {
	return false
}
