package item

import (
	"errors"
)

type ContactIdGetResponse_source_type int

const (
	APPOINTMENT_CONTACTIDGETRESPONSE_SOURCE_TYPE ContactIdGetResponse_source_type = iota
	FORMAPIHOSTED_CONTACTIDGETRESPONSE_SOURCE_TYPE
	FORMAPIINTERNAL_CONTACTIDGETRESPONSE_SOURCE_TYPE
	WEBFORM_CONTACTIDGETRESPONSE_SOURCE_TYPE
	INTERNALFORM_CONTACTIDGETRESPONSE_SOURCE_TYPE
	LANDINGPAGE_CONTACTIDGETRESPONSE_SOURCE_TYPE
	IMPORT_CONTACTIDGETRESPONSE_SOURCE_TYPE
	MANUAL_CONTACTIDGETRESPONSE_SOURCE_TYPE
	API_CONTACTIDGETRESPONSE_SOURCE_TYPE
	OTHER_CONTACTIDGETRESPONSE_SOURCE_TYPE
	UNKNOWN_CONTACTIDGETRESPONSE_SOURCE_TYPE
)

func (i ContactIdGetResponse_source_type) String() string {
	return []string{"APPOINTMENT", "FORMAPIHOSTED", "FORMAPIINTERNAL", "WEBFORM", "INTERNALFORM", "LANDINGPAGE", "IMPORT", "MANUAL", "API", "OTHER", "UNKNOWN"}[i]
}
func ParseContactIdGetResponse_source_type(v string) (any, error) {
	result := APPOINTMENT_CONTACTIDGETRESPONSE_SOURCE_TYPE
	switch v {
	case "APPOINTMENT":
		result = APPOINTMENT_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "FORMAPIHOSTED":
		result = FORMAPIHOSTED_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "FORMAPIINTERNAL":
		result = FORMAPIINTERNAL_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "WEBFORM":
		result = WEBFORM_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "INTERNALFORM":
		result = INTERNALFORM_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "LANDINGPAGE":
		result = LANDINGPAGE_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "IMPORT":
		result = IMPORT_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "MANUAL":
		result = MANUAL_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "API":
		result = API_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "OTHER":
		result = OTHER_CONTACTIDGETRESPONSE_SOURCE_TYPE
	case "UNKNOWN":
		result = UNKNOWN_CONTACTIDGETRESPONSE_SOURCE_TYPE
	default:
		return 0, errors.New("Unknown ContactIdGetResponse_source_type value: " + v)
	}
	return &result, nil
}
func SerializeContactIdGetResponse_source_type(values []ContactIdGetResponse_source_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ContactIdGetResponse_source_type) isMultiValue() bool {
	return false
}
