package item

import (
	"errors"
)

type ContactIdPatchResponse_email_status int

const (
	UNENGAGEDMARKETABLE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS ContactIdPatchResponse_email_status = iota
	SINGLEOPTIN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	DOUBLEOPTIN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	CONFIRMED_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	UNENGAGEDNONMARKETABLE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	NONMARKETABLE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	LOCKDOWN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	BOUNCE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	HARDBOUNCE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	MANUAL_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	ADMIN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	SYSTEM_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	LISTUNSUBSCRIBE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	FEEDBACK_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	SPAM_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	INVALID_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	DEACTIVATED_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
)

func (i ContactIdPatchResponse_email_status) String() string {
	return []string{"UnengagedMarketable", "SingleOptIn", "DoubleOptin", "Confirmed", "UnengagedNonMarketable", "NonMarketable", "Lockdown", "Bounce", "HardBounce", "Manual", "Admin", "System", "ListUnsubscribe", "Feedback", "Spam", "Invalid", "Deactivated"}[i]
}
func ParseContactIdPatchResponse_email_status(v string) (any, error) {
	result := UNENGAGEDMARKETABLE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	switch v {
	case "UnengagedMarketable":
		result = UNENGAGEDMARKETABLE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "SingleOptIn":
		result = SINGLEOPTIN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "DoubleOptin":
		result = DOUBLEOPTIN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Confirmed":
		result = CONFIRMED_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "UnengagedNonMarketable":
		result = UNENGAGEDNONMARKETABLE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "NonMarketable":
		result = NONMARKETABLE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Lockdown":
		result = LOCKDOWN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Bounce":
		result = BOUNCE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "HardBounce":
		result = HARDBOUNCE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Manual":
		result = MANUAL_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Admin":
		result = ADMIN_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "System":
		result = SYSTEM_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "ListUnsubscribe":
		result = LISTUNSUBSCRIBE_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Feedback":
		result = FEEDBACK_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Spam":
		result = SPAM_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Invalid":
		result = INVALID_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	case "Deactivated":
		result = DEACTIVATED_CONTACTIDPATCHRESPONSE_EMAIL_STATUS
	default:
		return 0, errors.New("Unknown ContactIdPatchResponse_email_status value: " + v)
	}
	return &result, nil
}
func SerializeContactIdPatchResponse_email_status(values []ContactIdPatchResponse_email_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ContactIdPatchResponse_email_status) isMultiValue() bool {
	return false
}
