package model

import (
	"errors"
)

type ModelGetResponse_custom_fields_field_type int

const (
	CURRENCY_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE ModelGetResponse_custom_fields_field_type = iota
	DATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DATE_TIME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DAY_OF_WEEK_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DECIMAL_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DRILLDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DROPDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	EMAIL_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	LIST_BOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	MONTH_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	NAME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	PERCENT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	PHONE_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	RADIO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	SOCIAL_SECURITY_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	STATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	TEXT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	TEXT_AREA_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	USER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	USER_LIST_BOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	WEBSITE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	WHOLE_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	YEAR_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	YES_NO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
)

func (i ModelGetResponse_custom_fields_field_type) String() string {
	return []string{"CURRENCY", "DATE", "DATE_TIME", "DAY_OF_WEEK", "DECIMAL_NUMBER", "DRILLDOWN", "DROPDOWN", "EMAIL", "LIST_BOX", "MONTH", "NAME", "PERCENT", "PHONE_NUMBER", "RADIO", "SOCIAL_SECURITY_NUMBER", "STATE", "TEXT", "TEXT_AREA", "USER", "USER_LIST_BOX", "WEBSITE", "WHOLE_NUMBER", "YEAR", "YES_NO"}[i]
}
func ParseModelGetResponse_custom_fields_field_type(v string) (any, error) {
	result := CURRENCY_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	switch v {
	case "CURRENCY":
		result = CURRENCY_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DATE":
		result = DATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DATE_TIME":
		result = DATE_TIME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DAY_OF_WEEK":
		result = DAY_OF_WEEK_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DECIMAL_NUMBER":
		result = DECIMAL_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DRILLDOWN":
		result = DRILLDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DROPDOWN":
		result = DROPDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "EMAIL":
		result = EMAIL_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "LIST_BOX":
		result = LIST_BOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "MONTH":
		result = MONTH_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "NAME":
		result = NAME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "PERCENT":
		result = PERCENT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "PHONE_NUMBER":
		result = PHONE_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "RADIO":
		result = RADIO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "SOCIAL_SECURITY_NUMBER":
		result = SOCIAL_SECURITY_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "STATE":
		result = STATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "TEXT":
		result = TEXT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "TEXT_AREA":
		result = TEXT_AREA_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "USER":
		result = USER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "USER_LIST_BOX":
		result = USER_LIST_BOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "WEBSITE":
		result = WEBSITE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "WHOLE_NUMBER":
		result = WHOLE_NUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "YEAR":
		result = YEAR_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "YES_NO":
		result = YES_NO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	default:
		return 0, errors.New("Unknown ModelGetResponse_custom_fields_field_type value: " + v)
	}
	return &result, nil
}
func SerializeModelGetResponse_custom_fields_field_type(values []ModelGetResponse_custom_fields_field_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ModelGetResponse_custom_fields_field_type) isMultiValue() bool {
	return false
}
