package item

import (
	"errors"
)

type WithFilePutResponse_file_descriptor_file_box_type int

const (
	APPLICATION_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE WithFilePutResponse_file_descriptor_file_box_type = iota
	IMAGE_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	FAX_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	ATTACHMENT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	TICKET_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	CONTACT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	DIGITALPRODUCT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	IMPORT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	HIDDEN_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	WEBFORM_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	STYLEDCART_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	RESAMPLEDIMAGE_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	TEMPLATETHUMBNAIL_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	FUNNEL_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	LOGOTHUMBNAIL_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	UNLAYER_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
)

func (i WithFilePutResponse_file_descriptor_file_box_type) String() string {
	return []string{"Application", "Image", "Fax", "Attachment", "Ticket", "Contact", "DigitalProduct", "Import", "Hidden", "WebForm", "StyledCart", "ReSampledImage", "TemplateThumbnail", "Funnel", "LogoThumbnail", "Unlayer"}[i]
}
func ParseWithFilePutResponse_file_descriptor_file_box_type(v string) (any, error) {
	result := APPLICATION_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	switch v {
	case "Application":
		result = APPLICATION_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Image":
		result = IMAGE_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Fax":
		result = FAX_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Attachment":
		result = ATTACHMENT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Ticket":
		result = TICKET_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Contact":
		result = CONTACT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "DigitalProduct":
		result = DIGITALPRODUCT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Import":
		result = IMPORT_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Hidden":
		result = HIDDEN_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "WebForm":
		result = WEBFORM_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "StyledCart":
		result = STYLEDCART_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "ReSampledImage":
		result = RESAMPLEDIMAGE_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "TemplateThumbnail":
		result = TEMPLATETHUMBNAIL_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Funnel":
		result = FUNNEL_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "LogoThumbnail":
		result = LOGOTHUMBNAIL_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Unlayer":
		result = UNLAYER_WITHFILEPUTRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	default:
		return 0, errors.New("Unknown WithFilePutResponse_file_descriptor_file_box_type value: " + v)
	}
	return &result, nil
}
func SerializeWithFilePutResponse_file_descriptor_file_box_type(values []WithFilePutResponse_file_descriptor_file_box_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i WithFilePutResponse_file_descriptor_file_box_type) isMultiValue() bool {
	return false
}
