package item

import (
	"errors"
)

type WithFileGetResponse_file_descriptor_file_box_type int

const (
	APPLICATION_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE WithFileGetResponse_file_descriptor_file_box_type = iota
	IMAGE_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	FAX_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	ATTACHMENT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	TICKET_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	CONTACT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	DIGITALPRODUCT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	IMPORT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	HIDDEN_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	WEBFORM_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	STYLEDCART_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	RESAMPLEDIMAGE_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	TEMPLATETHUMBNAIL_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	FUNNEL_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	LOGOTHUMBNAIL_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	UNLAYER_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
)

func (i WithFileGetResponse_file_descriptor_file_box_type) String() string {
	return []string{"Application", "Image", "Fax", "Attachment", "Ticket", "Contact", "DigitalProduct", "Import", "Hidden", "WebForm", "StyledCart", "ReSampledImage", "TemplateThumbnail", "Funnel", "LogoThumbnail", "Unlayer"}[i]
}
func ParseWithFileGetResponse_file_descriptor_file_box_type(v string) (any, error) {
	result := APPLICATION_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	switch v {
	case "Application":
		result = APPLICATION_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Image":
		result = IMAGE_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Fax":
		result = FAX_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Attachment":
		result = ATTACHMENT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Ticket":
		result = TICKET_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Contact":
		result = CONTACT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "DigitalProduct":
		result = DIGITALPRODUCT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Import":
		result = IMPORT_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Hidden":
		result = HIDDEN_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "WebForm":
		result = WEBFORM_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "StyledCart":
		result = STYLEDCART_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "ReSampledImage":
		result = RESAMPLEDIMAGE_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "TemplateThumbnail":
		result = TEMPLATETHUMBNAIL_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Funnel":
		result = FUNNEL_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "LogoThumbnail":
		result = LOGOTHUMBNAIL_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	case "Unlayer":
		result = UNLAYER_WITHFILEGETRESPONSE_FILE_DESCRIPTOR_FILE_BOX_TYPE
	default:
		return 0, errors.New("Unknown WithFileGetResponse_file_descriptor_file_box_type value: " + v)
	}
	return &result, nil
}
func SerializeWithFileGetResponse_file_descriptor_file_box_type(values []WithFileGetResponse_file_descriptor_file_box_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i WithFileGetResponse_file_descriptor_file_box_type) isMultiValue() bool {
	return false
}
