package item

import (
	"errors"
)

type WithContact_PatchResponse_email_addresses_email_opt_status int

const (
	UNENGAGED_MARKETABLE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS WithContact_PatchResponse_email_addresses_email_opt_status = iota
	SINGLE_OPT_IN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	DOUBLE_OPT_IN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	CONFIRMED_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	UNENGAGED_NON_MARKETABLE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	NON_MARKETABLE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	LOCKDOWN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	BOUNCE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	HARD_BOUNCE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	MANUAL_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	ADMIN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	SYSTEM_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	LIST_UNSUBSCRIBE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	FEEDBACK_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	SPAM_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	INVALID_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	DEACTIVATED_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
)

func (i WithContact_PatchResponse_email_addresses_email_opt_status) String() string {
	return []string{"UNENGAGED_MARKETABLE", "SINGLE_OPT_IN", "DOUBLE_OPT_IN", "CONFIRMED", "UNENGAGED_NON_MARKETABLE", "NON_MARKETABLE", "LOCKDOWN", "BOUNCE", "HARD_BOUNCE", "MANUAL", "ADMIN", "SYSTEM", "LIST_UNSUBSCRIBE", "FEEDBACK", "SPAM", "INVALID", "DEACTIVATED"}[i]
}
func ParseWithContact_PatchResponse_email_addresses_email_opt_status(v string) (any, error) {
	result := UNENGAGED_MARKETABLE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	switch v {
	case "UNENGAGED_MARKETABLE":
		result = UNENGAGED_MARKETABLE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SINGLE_OPT_IN":
		result = SINGLE_OPT_IN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "DOUBLE_OPT_IN":
		result = DOUBLE_OPT_IN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "CONFIRMED":
		result = CONFIRMED_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "UNENGAGED_NON_MARKETABLE":
		result = UNENGAGED_NON_MARKETABLE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "NON_MARKETABLE":
		result = NON_MARKETABLE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "LOCKDOWN":
		result = LOCKDOWN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "BOUNCE":
		result = BOUNCE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "HARD_BOUNCE":
		result = HARD_BOUNCE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "MANUAL":
		result = MANUAL_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "ADMIN":
		result = ADMIN_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SYSTEM":
		result = SYSTEM_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "LIST_UNSUBSCRIBE":
		result = LIST_UNSUBSCRIBE_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "FEEDBACK":
		result = FEEDBACK_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SPAM":
		result = SPAM_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "INVALID":
		result = INVALID_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "DEACTIVATED":
		result = DEACTIVATED_WITHCONTACT_PATCHRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	default:
		return 0, errors.New("Unknown WithContact_PatchResponse_email_addresses_email_opt_status value: " + v)
	}
	return &result, nil
}
func SerializeWithContact_PatchResponse_email_addresses_email_opt_status(values []WithContact_PatchResponse_email_addresses_email_opt_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i WithContact_PatchResponse_email_addresses_email_opt_status) isMultiValue() bool {
	return false
}
