package customfields

import (
	"errors"
)

type CustomFieldsPostResponse_field_type int

const (
	CURRENCY_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE CustomFieldsPostResponse_field_type = iota
	DATE_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	DATETIME_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	DAYOFWEEK_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	DRILLDOWN_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	EMAIL_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	MONTH_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	LISTBOX_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	NAME_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	WHOLENUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	DECIMALNUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	PERCENT_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	PHONENUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	RADIO_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	DROPDOWN_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	SOCIALSECURITYNUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	STATE_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	TEXT_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	TEXTAREA_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	USER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	USERLISTBOX_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	WEBSITE_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	YEAR_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	YESNO_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
)

func (i CustomFieldsPostResponse_field_type) String() string {
	return []string{"Currency", "Date", "DateTime", "DayOfWeek", "Drilldown", "Email", "Month", "ListBox", "Name", "WholeNumber", "DecimalNumber", "Percent", "PhoneNumber", "Radio", "Dropdown", "SocialSecurityNumber", "State", "Text", "TextArea", "User", "UserListBox", "Website", "Year", "YesNo"}[i]
}
func ParseCustomFieldsPostResponse_field_type(v string) (any, error) {
	result := CURRENCY_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	switch v {
	case "Currency":
		result = CURRENCY_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Date":
		result = DATE_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "DateTime":
		result = DATETIME_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "DayOfWeek":
		result = DAYOFWEEK_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Drilldown":
		result = DRILLDOWN_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Email":
		result = EMAIL_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Month":
		result = MONTH_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "ListBox":
		result = LISTBOX_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Name":
		result = NAME_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "WholeNumber":
		result = WHOLENUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "DecimalNumber":
		result = DECIMALNUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Percent":
		result = PERCENT_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "PhoneNumber":
		result = PHONENUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Radio":
		result = RADIO_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Dropdown":
		result = DROPDOWN_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "SocialSecurityNumber":
		result = SOCIALSECURITYNUMBER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "State":
		result = STATE_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Text":
		result = TEXT_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "TextArea":
		result = TEXTAREA_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "User":
		result = USER_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "UserListBox":
		result = USERLISTBOX_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Website":
		result = WEBSITE_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "Year":
		result = YEAR_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	case "YesNo":
		result = YESNO_CUSTOMFIELDSPOSTRESPONSE_FIELD_TYPE
	default:
		return 0, errors.New("Unknown CustomFieldsPostResponse_field_type value: " + v)
	}
	return &result, nil
}
func SerializeCustomFieldsPostResponse_field_type(values []CustomFieldsPostResponse_field_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i CustomFieldsPostResponse_field_type) isMultiValue() bool {
	return false
}
