package companies

import (
	"errors"
)

type CompaniesGetResponse_companies_email_status int

const (
	UNENGAGEDMARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS CompaniesGetResponse_companies_email_status = iota
	SINGLEOPTIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	DOUBLEOPTIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	CONFIRMED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	UNENGAGEDNONMARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	NONMARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	LOCKDOWN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	BOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	HARDBOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	MANUAL_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	ADMIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	SYSTEM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	LISTUNSUBSCRIBE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	FEEDBACK_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	SPAM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	INVALID_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	DEACTIVATED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
)

func (i CompaniesGetResponse_companies_email_status) String() string {
	return []string{"UnengagedMarketable", "SingleOptIn", "DoubleOptin", "Confirmed", "UnengagedNonMarketable", "NonMarketable", "Lockdown", "Bounce", "HardBounce", "Manual", "Admin", "System", "ListUnsubscribe", "Feedback", "Spam", "Invalid", "Deactivated"}[i]
}
func ParseCompaniesGetResponse_companies_email_status(v string) (any, error) {
	result := UNENGAGEDMARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	switch v {
	case "UnengagedMarketable":
		result = UNENGAGEDMARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "SingleOptIn":
		result = SINGLEOPTIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "DoubleOptin":
		result = DOUBLEOPTIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Confirmed":
		result = CONFIRMED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "UnengagedNonMarketable":
		result = UNENGAGEDNONMARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "NonMarketable":
		result = NONMARKETABLE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Lockdown":
		result = LOCKDOWN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Bounce":
		result = BOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "HardBounce":
		result = HARDBOUNCE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Manual":
		result = MANUAL_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Admin":
		result = ADMIN_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "System":
		result = SYSTEM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "ListUnsubscribe":
		result = LISTUNSUBSCRIBE_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Feedback":
		result = FEEDBACK_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Spam":
		result = SPAM_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Invalid":
		result = INVALID_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	case "Deactivated":
		result = DEACTIVATED_COMPANIESGETRESPONSE_COMPANIES_EMAIL_STATUS
	default:
		return 0, errors.New("Unknown CompaniesGetResponse_companies_email_status value: " + v)
	}
	return &result, nil
}
func SerializeCompaniesGetResponse_companies_email_status(values []CompaniesGetResponse_companies_email_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i CompaniesGetResponse_companies_email_status) isMultiValue() bool {
	return false
}
