package item

import (
	"errors"
)

type WithCompanyPatchResponse_email_status int

const (
	UNENGAGEDMARKETABLE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS WithCompanyPatchResponse_email_status = iota
	SINGLEOPTIN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	DOUBLEOPTIN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	CONFIRMED_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	UNENGAGEDNONMARKETABLE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	NONMARKETABLE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	LOCKDOWN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	BOUNCE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	HARDBOUNCE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	MANUAL_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	ADMIN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	SYSTEM_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	LISTUNSUBSCRIBE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	FEEDBACK_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	SPAM_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	INVALID_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	DEACTIVATED_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
)

func (i WithCompanyPatchResponse_email_status) String() string {
	return []string{"UnengagedMarketable", "SingleOptIn", "DoubleOptin", "Confirmed", "UnengagedNonMarketable", "NonMarketable", "Lockdown", "Bounce", "HardBounce", "Manual", "Admin", "System", "ListUnsubscribe", "Feedback", "Spam", "Invalid", "Deactivated"}[i]
}
func ParseWithCompanyPatchResponse_email_status(v string) (any, error) {
	result := UNENGAGEDMARKETABLE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	switch v {
	case "UnengagedMarketable":
		result = UNENGAGEDMARKETABLE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "SingleOptIn":
		result = SINGLEOPTIN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "DoubleOptin":
		result = DOUBLEOPTIN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Confirmed":
		result = CONFIRMED_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "UnengagedNonMarketable":
		result = UNENGAGEDNONMARKETABLE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "NonMarketable":
		result = NONMARKETABLE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Lockdown":
		result = LOCKDOWN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Bounce":
		result = BOUNCE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "HardBounce":
		result = HARDBOUNCE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Manual":
		result = MANUAL_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Admin":
		result = ADMIN_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "System":
		result = SYSTEM_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "ListUnsubscribe":
		result = LISTUNSUBSCRIBE_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Feedback":
		result = FEEDBACK_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Spam":
		result = SPAM_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Invalid":
		result = INVALID_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	case "Deactivated":
		result = DEACTIVATED_WITHCOMPANYPATCHRESPONSE_EMAIL_STATUS
	default:
		return 0, errors.New("Unknown WithCompanyPatchResponse_email_status value: " + v)
	}
	return &result, nil
}
func SerializeWithCompanyPatchResponse_email_status(values []WithCompanyPatchResponse_email_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i WithCompanyPatchResponse_email_status) isMultiValue() bool {
	return false
}
