package item

import (
	"errors"
)

type WithCampaignGetResponse_sequences_paths_items_type int

const (
	START_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE WithCampaignGetResponse_sequences_paths_items_type = iota
	WAIT_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	DELAYTIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	CONTACTTIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	DATETIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	APPOINTMENTTIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	EMAIL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	BARDEMAIL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	UNLAYEREMAIL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	EMAILCONFIRM_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	VOICE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	FAX_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	LETTER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	AUTOMATEDSMS_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	TAG_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	OPPORTUNITY_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	NOTE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	TASK_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	COMPLETETASKS_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	APPOINTMENT_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	ASSIGNOWNER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	FIELDVALUE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	FULFILLMENT_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	CREATEORDER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	DEAL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	ADDTOSEQUENCE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	CANCELSUBSCRIPTION_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	MOVEOPPORTUNITY_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	HTTP_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	CUSTOMERHUB_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	HTTPREQUEST_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	ACTIONSET_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
)

func (i WithCampaignGetResponse_sequences_paths_items_type) String() string {
	return []string{"Start", "Wait", "DelayTimer", "ContactTimer", "DateTimer", "AppointmentTimer", "Email", "BardEmail", "UnlayerEmail", "EmailConfirm", "Voice", "Fax", "Letter", "AutomatedSms", "Tag", "Opportunity", "Note", "Task", "CompleteTasks", "Appointment", "AssignOwner", "FieldValue", "Fulfillment", "CreateOrder", "Deal", "AddToSequence", "CancelSubscription", "MoveOpportunity", "Http", "CustomerHub", "HttpRequest", "ActionSet"}[i]
}
func ParseWithCampaignGetResponse_sequences_paths_items_type(v string) (any, error) {
	result := START_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	switch v {
	case "Start":
		result = START_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Wait":
		result = WAIT_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "DelayTimer":
		result = DELAYTIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "ContactTimer":
		result = CONTACTTIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "DateTimer":
		result = DATETIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "AppointmentTimer":
		result = APPOINTMENTTIMER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Email":
		result = EMAIL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "BardEmail":
		result = BARDEMAIL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "UnlayerEmail":
		result = UNLAYEREMAIL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "EmailConfirm":
		result = EMAILCONFIRM_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Voice":
		result = VOICE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Fax":
		result = FAX_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Letter":
		result = LETTER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "AutomatedSms":
		result = AUTOMATEDSMS_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Tag":
		result = TAG_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Opportunity":
		result = OPPORTUNITY_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Note":
		result = NOTE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Task":
		result = TASK_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "CompleteTasks":
		result = COMPLETETASKS_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Appointment":
		result = APPOINTMENT_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "AssignOwner":
		result = ASSIGNOWNER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "FieldValue":
		result = FIELDVALUE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Fulfillment":
		result = FULFILLMENT_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "CreateOrder":
		result = CREATEORDER_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Deal":
		result = DEAL_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "AddToSequence":
		result = ADDTOSEQUENCE_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "CancelSubscription":
		result = CANCELSUBSCRIPTION_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "MoveOpportunity":
		result = MOVEOPPORTUNITY_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "Http":
		result = HTTP_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "CustomerHub":
		result = CUSTOMERHUB_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "HttpRequest":
		result = HTTPREQUEST_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	case "ActionSet":
		result = ACTIONSET_WITHCAMPAIGNGETRESPONSE_SEQUENCES_PATHS_ITEMS_TYPE
	default:
		return 0, errors.New("Unknown WithCampaignGetResponse_sequences_paths_items_type value: " + v)
	}
	return &result, nil
}
func SerializeWithCampaignGetResponse_sequences_paths_items_type(values []WithCampaignGetResponse_sequences_paths_items_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i WithCampaignGetResponse_sequences_paths_items_type) isMultiValue() bool {
	return false
}
