package contacts

import (
	"errors"
)

type ContactsGetResponse_contacts_email_status int

const (
	UNENGAGEDMARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS ContactsGetResponse_contacts_email_status = iota
	SINGLEOPTIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	DOUBLEOPTIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	CONFIRMED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	UNENGAGEDNONMARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	NONMARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	LOCKDOWN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	BOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	HARDBOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	MANUAL_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	ADMIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	SYSTEM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	LISTUNSUBSCRIBE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	FEEDBACK_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	SPAM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	INVALID_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	DEACTIVATED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
)

func (i ContactsGetResponse_contacts_email_status) String() string {
	return []string{"UnengagedMarketable", "SingleOptIn", "DoubleOptin", "Confirmed", "UnengagedNonMarketable", "NonMarketable", "Lockdown", "Bounce", "HardBounce", "Manual", "Admin", "System", "ListUnsubscribe", "Feedback", "Spam", "Invalid", "Deactivated"}[i]
}
func ParseContactsGetResponse_contacts_email_status(v string) (any, error) {
	result := UNENGAGEDMARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	switch v {
	case "UnengagedMarketable":
		result = UNENGAGEDMARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "SingleOptIn":
		result = SINGLEOPTIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "DoubleOptin":
		result = DOUBLEOPTIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Confirmed":
		result = CONFIRMED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "UnengagedNonMarketable":
		result = UNENGAGEDNONMARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "NonMarketable":
		result = NONMARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Lockdown":
		result = LOCKDOWN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Bounce":
		result = BOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "HardBounce":
		result = HARDBOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Manual":
		result = MANUAL_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Admin":
		result = ADMIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "System":
		result = SYSTEM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "ListUnsubscribe":
		result = LISTUNSUBSCRIBE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Feedback":
		result = FEEDBACK_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Spam":
		result = SPAM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Invalid":
		result = INVALID_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	case "Deactivated":
		result = DEACTIVATED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_STATUS
	default:
		return 0, errors.New("Unknown ContactsGetResponse_contacts_email_status value: " + v)
	}
	return &result, nil
}
func SerializeContactsGetResponse_contacts_email_status(values []ContactsGetResponse_contacts_email_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ContactsGetResponse_contacts_email_status) isMultiValue() bool {
	return false
}
