package contacts

import (
	"errors"
)

type ContactsPutRequestBody_source_type int

const (
	APPOINTMENT_CONTACTSPUTREQUESTBODY_SOURCE_TYPE ContactsPutRequestBody_source_type = iota
	FORMAPIHOSTED_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	FORMAPIINTERNAL_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	WEBFORM_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	INTERNALFORM_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	LANDINGPAGE_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	IMPORT_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	MANUAL_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	API_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	OTHER_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	UNKNOWN_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
)

func (i ContactsPutRequestBody_source_type) String() string {
	return []string{"APPOINTMENT", "FORMAPIHOSTED", "FORMAPIINTERNAL", "WEBFORM", "INTERNALFORM", "LANDINGPAGE", "IMPORT", "MANUAL", "API", "OTHER", "UNKNOWN"}[i]
}
func ParseContactsPutRequestBody_source_type(v string) (any, error) {
	result := APPOINTMENT_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	switch v {
	case "APPOINTMENT":
		result = APPOINTMENT_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "FORMAPIHOSTED":
		result = FORMAPIHOSTED_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "FORMAPIINTERNAL":
		result = FORMAPIINTERNAL_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "WEBFORM":
		result = WEBFORM_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "INTERNALFORM":
		result = INTERNALFORM_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "LANDINGPAGE":
		result = LANDINGPAGE_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "IMPORT":
		result = IMPORT_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "MANUAL":
		result = MANUAL_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "API":
		result = API_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "OTHER":
		result = OTHER_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	case "UNKNOWN":
		result = UNKNOWN_CONTACTSPUTREQUESTBODY_SOURCE_TYPE
	default:
		return 0, errors.New("Unknown ContactsPutRequestBody_source_type value: " + v)
	}
	return &result, nil
}
func SerializeContactsPutRequestBody_source_type(values []ContactsPutRequestBody_source_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ContactsPutRequestBody_source_type) isMultiValue() bool {
	return false
}
