package model

import (
	"errors"
)

type ModelGetResponse_custom_fields_field_type int

const (
	CURRENCY_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE ModelGetResponse_custom_fields_field_type = iota
	DATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DATETIME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DAYOFWEEK_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DRILLDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	EMAIL_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	MONTH_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	LISTBOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	NAME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	WHOLENUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DECIMALNUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	PERCENT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	PHONENUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	RADIO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	DROPDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	SOCIALSECURITYNUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	STATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	TEXT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	TEXTAREA_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	USER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	USERLISTBOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	WEBSITE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	YEAR_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	YESNO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
)

func (i ModelGetResponse_custom_fields_field_type) String() string {
	return []string{"Currency", "Date", "DateTime", "DayOfWeek", "Drilldown", "Email", "Month", "ListBox", "Name", "WholeNumber", "DecimalNumber", "Percent", "PhoneNumber", "Radio", "Dropdown", "SocialSecurityNumber", "State", "Text", "TextArea", "User", "UserListBox", "Website", "Year", "YesNo"}[i]
}
func ParseModelGetResponse_custom_fields_field_type(v string) (any, error) {
	result := CURRENCY_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	switch v {
	case "Currency":
		result = CURRENCY_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Date":
		result = DATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DateTime":
		result = DATETIME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DayOfWeek":
		result = DAYOFWEEK_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Drilldown":
		result = DRILLDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Email":
		result = EMAIL_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Month":
		result = MONTH_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "ListBox":
		result = LISTBOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Name":
		result = NAME_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "WholeNumber":
		result = WHOLENUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "DecimalNumber":
		result = DECIMALNUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Percent":
		result = PERCENT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "PhoneNumber":
		result = PHONENUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Radio":
		result = RADIO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Dropdown":
		result = DROPDOWN_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "SocialSecurityNumber":
		result = SOCIALSECURITYNUMBER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "State":
		result = STATE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Text":
		result = TEXT_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "TextArea":
		result = TEXTAREA_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "User":
		result = USER_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "UserListBox":
		result = USERLISTBOX_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Website":
		result = WEBSITE_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "Year":
		result = YEAR_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	case "YesNo":
		result = YESNO_MODELGETRESPONSE_CUSTOM_FIELDS_FIELD_TYPE
	default:
		return 0, errors.New("Unknown ModelGetResponse_custom_fields_field_type value: " + v)
	}
	return &result, nil
}
func SerializeModelGetResponse_custom_fields_field_type(values []ModelGetResponse_custom_fields_field_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ModelGetResponse_custom_fields_field_type) isMultiValue() bool {
	return false
}
