package item

import (
	"errors"
)

type WithCampaign_GetResponse_goals_type int

const (
	WEBFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE WithCampaign_GetResponse_goals_type = iota
	LANDINGPAGE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	SURVEY_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	LINKCLICK_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	EMAILOPENED_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	SCORE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	PURCHASE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	FAILEDPURCHASE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	QUOTE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	WEBSITETRIGGER_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	INTERNALFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	SMARTFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	APPOINTMENTEVENT_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	TASK_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	STAGEMOVE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	NOTE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	TAG_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	PIPELINESTAGEMOVE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	UNLAYERLANDINGPAGE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	GROSOCIAL_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	TWITTERFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	API_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	WORDPRESS_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	NEWLANDINGPAGE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	INTEGRATIONTRIGGER_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
)

func (i WithCampaign_GetResponse_goals_type) String() string {
	return []string{"WebForm", "LandingPage", "Survey", "LinkClick", "EmailOpened", "Score", "Purchase", "FailedPurchase", "Quote", "WebsiteTrigger", "InternalForm", "SmartForm", "AppointmentEvent", "Task", "StageMove", "Note", "Tag", "PipelineStageMove", "UnlayerLandingPage", "GroSocial", "TwitterForm", "API", "WordPress", "NewLandingPage", "IntegrationTrigger"}[i]
}
func ParseWithCampaign_GetResponse_goals_type(v string) (any, error) {
	result := WEBFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	switch v {
	case "WebForm":
		result = WEBFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "LandingPage":
		result = LANDINGPAGE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "Survey":
		result = SURVEY_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "LinkClick":
		result = LINKCLICK_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "EmailOpened":
		result = EMAILOPENED_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "Score":
		result = SCORE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "Purchase":
		result = PURCHASE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "FailedPurchase":
		result = FAILEDPURCHASE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "Quote":
		result = QUOTE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "WebsiteTrigger":
		result = WEBSITETRIGGER_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "InternalForm":
		result = INTERNALFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "SmartForm":
		result = SMARTFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "AppointmentEvent":
		result = APPOINTMENTEVENT_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "Task":
		result = TASK_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "StageMove":
		result = STAGEMOVE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "Note":
		result = NOTE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "Tag":
		result = TAG_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "PipelineStageMove":
		result = PIPELINESTAGEMOVE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "UnlayerLandingPage":
		result = UNLAYERLANDINGPAGE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "GroSocial":
		result = GROSOCIAL_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "TwitterForm":
		result = TWITTERFORM_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "API":
		result = API_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "WordPress":
		result = WORDPRESS_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "NewLandingPage":
		result = NEWLANDINGPAGE_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	case "IntegrationTrigger":
		result = INTEGRATIONTRIGGER_WITHCAMPAIGN_GETRESPONSE_GOALS_TYPE
	default:
		return 0, errors.New("Unknown WithCampaign_GetResponse_goals_type value: " + v)
	}
	return &result, nil
}
func SerializeWithCampaign_GetResponse_goals_type(values []WithCampaign_GetResponse_goals_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i WithCampaign_GetResponse_goals_type) isMultiValue() bool {
	return false
}
