package contacts

import (
	"errors"
)

type ContactsPostResponse_email_addresses_email_opt_status int

const (
	UNENGAGED_MARKETABLE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS ContactsPostResponse_email_addresses_email_opt_status = iota
	SINGLE_OPT_IN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	DOUBLE_OPT_IN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	CONFIRMED_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	UNENGAGED_NON_MARKETABLE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	NON_MARKETABLE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	LOCKDOWN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	BOUNCE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	HARD_BOUNCE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	MANUAL_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	ADMIN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	SYSTEM_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	LIST_UNSUBSCRIBE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	FEEDBACK_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	SPAM_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	INVALID_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	DEACTIVATED_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
)

func (i ContactsPostResponse_email_addresses_email_opt_status) String() string {
	return []string{"UNENGAGED_MARKETABLE", "SINGLE_OPT_IN", "DOUBLE_OPT_IN", "CONFIRMED", "UNENGAGED_NON_MARKETABLE", "NON_MARKETABLE", "LOCKDOWN", "BOUNCE", "HARD_BOUNCE", "MANUAL", "ADMIN", "SYSTEM", "LIST_UNSUBSCRIBE", "FEEDBACK", "SPAM", "INVALID", "DEACTIVATED"}[i]
}
func ParseContactsPostResponse_email_addresses_email_opt_status(v string) (any, error) {
	result := UNENGAGED_MARKETABLE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	switch v {
	case "UNENGAGED_MARKETABLE":
		result = UNENGAGED_MARKETABLE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SINGLE_OPT_IN":
		result = SINGLE_OPT_IN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "DOUBLE_OPT_IN":
		result = DOUBLE_OPT_IN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "CONFIRMED":
		result = CONFIRMED_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "UNENGAGED_NON_MARKETABLE":
		result = UNENGAGED_NON_MARKETABLE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "NON_MARKETABLE":
		result = NON_MARKETABLE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "LOCKDOWN":
		result = LOCKDOWN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "BOUNCE":
		result = BOUNCE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "HARD_BOUNCE":
		result = HARD_BOUNCE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "MANUAL":
		result = MANUAL_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "ADMIN":
		result = ADMIN_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SYSTEM":
		result = SYSTEM_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "LIST_UNSUBSCRIBE":
		result = LIST_UNSUBSCRIBE_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "FEEDBACK":
		result = FEEDBACK_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SPAM":
		result = SPAM_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "INVALID":
		result = INVALID_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "DEACTIVATED":
		result = DEACTIVATED_CONTACTSPOSTRESPONSE_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	default:
		return 0, errors.New("Unknown ContactsPostResponse_email_addresses_email_opt_status value: " + v)
	}
	return &result, nil
}
func SerializeContactsPostResponse_email_addresses_email_opt_status(values []ContactsPostResponse_email_addresses_email_opt_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ContactsPostResponse_email_addresses_email_opt_status) isMultiValue() bool {
	return false
}
