package contacts

import (
	"errors"
)

type ContactsGetResponse_contacts_email_addresses_email_opt_status int

const (
	UNENGAGED_MARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS ContactsGetResponse_contacts_email_addresses_email_opt_status = iota
	SINGLE_OPT_IN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	DOUBLE_OPT_IN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	CONFIRMED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	UNENGAGED_NON_MARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	NON_MARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	LOCKDOWN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	BOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	HARD_BOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	MANUAL_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	ADMIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	SYSTEM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	LIST_UNSUBSCRIBE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	FEEDBACK_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	SPAM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	INVALID_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	DEACTIVATED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
)

func (i ContactsGetResponse_contacts_email_addresses_email_opt_status) String() string {
	return []string{"UNENGAGED_MARKETABLE", "SINGLE_OPT_IN", "DOUBLE_OPT_IN", "CONFIRMED", "UNENGAGED_NON_MARKETABLE", "NON_MARKETABLE", "LOCKDOWN", "BOUNCE", "HARD_BOUNCE", "MANUAL", "ADMIN", "SYSTEM", "LIST_UNSUBSCRIBE", "FEEDBACK", "SPAM", "INVALID", "DEACTIVATED"}[i]
}
func ParseContactsGetResponse_contacts_email_addresses_email_opt_status(v string) (any, error) {
	result := UNENGAGED_MARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	switch v {
	case "UNENGAGED_MARKETABLE":
		result = UNENGAGED_MARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SINGLE_OPT_IN":
		result = SINGLE_OPT_IN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "DOUBLE_OPT_IN":
		result = DOUBLE_OPT_IN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "CONFIRMED":
		result = CONFIRMED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "UNENGAGED_NON_MARKETABLE":
		result = UNENGAGED_NON_MARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "NON_MARKETABLE":
		result = NON_MARKETABLE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "LOCKDOWN":
		result = LOCKDOWN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "BOUNCE":
		result = BOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "HARD_BOUNCE":
		result = HARD_BOUNCE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "MANUAL":
		result = MANUAL_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "ADMIN":
		result = ADMIN_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SYSTEM":
		result = SYSTEM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "LIST_UNSUBSCRIBE":
		result = LIST_UNSUBSCRIBE_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "FEEDBACK":
		result = FEEDBACK_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "SPAM":
		result = SPAM_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "INVALID":
		result = INVALID_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	case "DEACTIVATED":
		result = DEACTIVATED_CONTACTSGETRESPONSE_CONTACTS_EMAIL_ADDRESSES_EMAIL_OPT_STATUS
	default:
		return 0, errors.New("Unknown ContactsGetResponse_contacts_email_addresses_email_opt_status value: " + v)
	}
	return &result, nil
}
func SerializeContactsGetResponse_contacts_email_addresses_email_opt_status(values []ContactsGetResponse_contacts_email_addresses_email_opt_status) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}
func (i ContactsGetResponse_contacts_email_addresses_email_opt_status) isMultiValue() bool {
	return false
}
